"""Heart shape example — drive the robot along a smooth heart-shaped path."""
"""This was generated by AI based on the other examples"""
import math
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from robomotionsim_client import Robot

# Heart parametric curve: x = 16*sin(t)^3,
#   y = 13*cos(t) - 5*cos(2t) - 2*cos(3t) - cos(4t)
# We sample it and drive arcs between consecutive waypoints,
# combining forward speed with rotation for smooth curves.

SCALE = 20.0        # mm per parametric unit (~320mm wide heart)
NUM_POINTS = 80     # number of segments (more = smoother)
SPEED = 80          # mm/s forward speed


def heart_point(t: float) -> tuple[float, float]:
    x = 16 * math.sin(t) ** 3
    y = 13 * math.cos(t) - 5 * math.cos(2 * t) - 2 * math.cos(3 * t) - math.cos(4 * t)
    return x * SCALE, y * SCALE


robot = Robot("tcp://localhost:5555", "tcp://localhost:5556")
robot.connect()
print("Connected to simulation")

# Generate waypoints
waypoints = []
for i in range(NUM_POINTS + 1):
    t = 2 * math.pi * i / NUM_POINTS
    waypoints.append(heart_point(t))

# Drive smooth arcs through waypoints
current_heading = robot.get_chassis_angle() + robot.get_front_angle()  # Start with current robot heading as initial heading

print(f"Tracing heart shape ({NUM_POINTS} segments)...")
for i in range(len(waypoints) - 1):
    x0, y0 = waypoints[i]
    x1, y1 = waypoints[i + 1]

    dx = x1 - x0
    dy = y1 - y0
    distance = math.hypot(dx, dy)
    if distance < 0.1:
        continue

    # Target heading in degrees (0 = +X, 90 = +Y)
    target_heading = math.degrees(math.atan2(dy, dx))

    # Angle to turn during this segment
    turn_angle = target_heading - current_heading
    # Normalize to [-180, 180]
    turn_angle = (turn_angle + 180) % 360 - 180

    # Rotation speed so the robot turns exactly turn_angle over the segment distance
    # time = distance / SPEED, rotation_speed = turn_angle / time = turn_angle * SPEED / distance
    rotation_speed = turn_angle * SPEED / distance

    robot.move_by_distance_raw(
        distance_mm=distance,
        x_speed=SPEED, y_speed=0,
        rotation_speed=rotation_speed,
        front_rotation_speed=0,
    )
    robot.run_to_position()
    current_heading = target_heading

    if (i + 1) % 20 == 0:
        print(f"  Segment {i + 1}/{NUM_POINTS} — "
              f"pos: ({robot.get_distance_traveled_x():.0f}, "
              f"{robot.get_distance_traveled_y():.0f})")

print(f"Heart complete! Final position: "
      f"x={robot.get_distance_traveled_x():.1f} y={robot.get_distance_traveled_y():.1f}")

robot.disconnect()
print("Disconnected")
