"""Test all robot commands — runs each command and prints telemetry to verify."""
"""This was generated by AI based on the other examples, to cover all commands and some error cases."""

import sys
import os
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from robomotionsim_client import Robot
from robomotionsim_client.robot import RobotCommandError

robot = Robot("tcp://localhost:5555", "tcp://localhost:5556")
robot.connect()
print("Connected to simulation\n")

passed = 0
failed = 0


def status():
    robot.run()
    return (f"x={robot.get_distance_traveled_x():.1f} "
            f"y={robot.get_distance_traveled_y():.1f} "
            f"angle={robot.get_chassis_angle():.1f}")


def test(name, fn, check=None):
    global passed, failed
    print(f"[TEST] {name}")
    before = status()
    try:
        fn()
        after = status()
        if check:
            ok, msg = check()
            if ok:
                print(f"  PASS — {msg}")
                passed += 1
            else:
                print(f"  FAIL — {msg}")
                failed += 1
        else:
            print(f"  DONE — before: {before}")
            print(f"         after:  {after}")
            passed += 1
    except Exception as e:
        print(f"  FAIL — {e}")
        failed += 1
    print()


def test_expect_error(name, fn):
    """Test that expects an error from the simulator (CMD_ERROR)."""
    global passed, failed
    print(f"[TEST] {name}")
    try:
        fn()
        # If we get here with no exception, the command was accepted but may
        # still fail — drain messages briefly to catch CMD_ERROR
        start = time.monotonic()
        while time.monotonic() - start < 1.0:
            robot.run()
            time.sleep(0.02)
        print(f"  FAIL — expected error but command succeeded")
        failed += 1
    except (RobotCommandError, Exception) as e:
        print(f"  PASS — got expected error: {e}")
        passed += 1
    print()


# ================================================================
#  RAW DISTANCE COMMANDS
# ================================================================

# 1. Forward
def test_dist_raw_forward():
    robot.move_by_distance_raw(distance_mm=200, x_speed=100, y_speed=0,
                               rotation_speed=0, front_rotation_speed=0)
    robot.run_to_position()

test("move_by_distance_raw — forward 200mm", test_dist_raw_forward)

# 2. Backward (negative x_speed)
def test_dist_raw_backward():
    x0 = robot.get_distance_traveled_x()
    robot.move_by_distance_raw(distance_mm=150, x_speed=-100, y_speed=0,
                               rotation_speed=0, front_rotation_speed=0)
    robot.run_to_position()

test("move_by_distance_raw — backward 150mm", test_dist_raw_backward)

# 3. Lateral (y_speed only)
def test_dist_raw_lateral():
    robot.move_by_distance_raw(distance_mm=200, x_speed=0, y_speed=100,
                               rotation_speed=0, front_rotation_speed=0)
    robot.run_to_position()

test("move_by_distance_raw — lateral 200mm (y only)", test_dist_raw_lateral)

# 4. Diagonal
def test_dist_raw_diagonal():
    robot.move_by_distance_raw(distance_mm=250, x_speed=80, y_speed=60,
                               rotation_speed=0, front_rotation_speed=0)
    robot.run_to_position()

test("move_by_distance_raw — diagonal (80x, 60y) 250mm", test_dist_raw_diagonal)

# 5. With rotation while moving
def test_dist_raw_with_rotation():
    robot.move_by_distance_raw(distance_mm=300, x_speed=100, y_speed=0,
                               rotation_speed=30, front_rotation_speed=0)
    robot.run_to_position()

test("move_by_distance_raw — forward 300mm + rotating 30deg/s", test_dist_raw_with_rotation)

# 6. With front rotation
def test_dist_raw_front_rotation():
    robot.move_by_distance_raw(distance_mm=200, x_speed=100, y_speed=0,
                               rotation_speed=0, front_rotation_speed=45)
    robot.run_to_position()

test("move_by_distance_raw — forward 200mm + front rotation 45deg/s", test_dist_raw_front_rotation)


# ================================================================
#  RAW TIME COMMANDS
# ================================================================

# 7. Forward
def test_time_raw_forward():
    robot.move_by_time_raw(time_s=1.0, x_speed=100, y_speed=0,
                           rotation_speed=0, front_rotation_speed=0)
    robot.run_to_position()

test("move_by_time_raw — forward 1s at 100mm/s", test_time_raw_forward)

# 8. Backward
def test_time_raw_backward():
    robot.move_by_time_raw(time_s=0.5, x_speed=-150, y_speed=0,
                           rotation_speed=0, front_rotation_speed=0)
    robot.run_to_position()

test("move_by_time_raw — backward 0.5s at -150mm/s", test_time_raw_backward)

# 9. Spin in place
def test_time_raw_spin():
    a0 = robot.get_chassis_angle()
    robot.move_by_time_raw(time_s=1.0, x_speed=0, y_speed=0,
                           rotation_speed=90, front_rotation_speed=0)
    robot.run_to_position()

def check_time_spin():
    a = robot.get_chassis_angle()
    return (True, f"chassis_angle={a:.1f}")

test("move_by_time_raw — spin 90deg/s for 1s", test_time_raw_spin, check_time_spin)

# 10. Diagonal + rotation
def test_time_raw_complex():
    robot.move_by_time_raw(time_s=1.0, x_speed=50, y_speed=50,
                           rotation_speed=45, front_rotation_speed=20)
    robot.run_to_position()

test("move_by_time_raw — diagonal + rotation + front rotation 1s", test_time_raw_complex)


# ================================================================
#  RAW ANGLE COMMANDS
# ================================================================

# 11. Positive angle
def test_angle_raw_pos():
    robot.move_by_angle_raw(angle_deg=90, x_speed=0, y_speed=0,
                            rotation_speed=50, front_rotation_speed=0)
    robot.run_to_position()

def check_angle_pos():
    a = robot.get_chassis_angle()
    return (True, f"chassis_angle={a:.1f}")

test("move_by_angle_raw — turn +90 deg", test_angle_raw_pos, check_angle_pos)

# 12. Negative angle (tests the simulator fix)
def test_angle_raw_neg():
    robot.move_by_angle_raw(angle_deg=-90, x_speed=0, y_speed=0,
                            rotation_speed=50, front_rotation_speed=0)
    robot.run_to_position()

def check_angle_neg():
    a = robot.get_chassis_angle()
    return (True, f"chassis_angle={a:.1f}")

test("move_by_angle_raw — turn -90 deg", test_angle_raw_neg, check_angle_neg)

# 13. Small positive angle
def test_angle_raw_small_pos():
    a0 = robot.get_chassis_angle()
    robot.move_by_angle_raw(angle_deg=10, x_speed=0, y_speed=0,
                            rotation_speed=30, front_rotation_speed=0)
    robot.run_to_position()

def check_angle_small_pos():
    a = robot.get_chassis_angle()
    return (True, f"chassis_angle={a:.1f}")

test("move_by_angle_raw — turn +10 deg (small)", test_angle_raw_small_pos, check_angle_small_pos)

# 14. Small negative angle
def test_angle_raw_small_neg():
    a0 = robot.get_chassis_angle()
    robot.move_by_angle_raw(angle_deg=-10, x_speed=0, y_speed=0,
                            rotation_speed=30, front_rotation_speed=0)
    robot.run_to_position()

def check_angle_small_neg():
    a = robot.get_chassis_angle()
    return (True, f"chassis_angle={a:.1f}")

test("move_by_angle_raw — turn -10 deg (small)", test_angle_raw_small_neg, check_angle_small_neg)

# 15. Large angle (270 deg)
def test_angle_raw_large():
    robot.move_by_angle_raw(angle_deg=270, x_speed=0, y_speed=0,
                            rotation_speed=90, front_rotation_speed=0)
    robot.run_to_position()

def check_angle_large():
    a = robot.get_chassis_angle()
    return (True, f"chassis_angle={a:.1f}")

test("move_by_angle_raw — turn +270 deg (large)", test_angle_raw_large, check_angle_large)

# 16. Large negative angle (-270 deg)
def test_angle_raw_large_neg():
    robot.move_by_angle_raw(angle_deg=-270, x_speed=0, y_speed=0,
                            rotation_speed=90, front_rotation_speed=0)
    robot.run_to_position()

def check_angle_large_neg():
    a = robot.get_chassis_angle()
    return (True, f"chassis_angle={a:.1f}")

test("move_by_angle_raw — turn -270 deg (large)", test_angle_raw_large_neg, check_angle_large_neg)

# 17. Angle with forward motion (arc)
def test_angle_raw_arc():
    robot.move_by_angle_raw(angle_deg=45, x_speed=80, y_speed=0,
                            rotation_speed=30, front_rotation_speed=0)
    robot.run_to_position()

test("move_by_angle_raw — arc: +45 deg while moving forward", test_angle_raw_arc)

# 18. Angle with front rotation
def test_angle_raw_front():
    robot.move_by_angle_raw(angle_deg=60, x_speed=0, y_speed=0,
                            rotation_speed=40, front_rotation_speed=20)
    robot.run_to_position()

def check_angle_front():
    a = robot.get_chassis_angle()
    f = robot.get_front_angle()
    return (True, f"chassis={a:.1f} front={f:.1f}")

test("move_by_angle_raw — +60 deg with front rotation", test_angle_raw_front, check_angle_front)


# ================================================================
#  RAW SPEED COMMANDS
# ================================================================

# 19. Forward speed + stop
def test_speed_raw_forward():
    robot.move_at_speed_raw(x_speed=150, y_speed=0,
                            rotation_speed=0, front_rotation_speed=0)
    start = time.monotonic()
    while time.monotonic() - start < 1.0:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

test("move_at_speed_raw — forward 150mm/s for 1s + stop", test_speed_raw_forward)

# 20. Rotation speed only
def test_speed_raw_spin():
    robot.move_at_speed_raw(x_speed=0, y_speed=0,
                            rotation_speed=120, front_rotation_speed=0)
    start = time.monotonic()
    while time.monotonic() - start < 0.5:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

test("move_at_speed_raw — spin 120deg/s for 0.5s + stop", test_speed_raw_spin)

# 21. Negative speeds
def test_speed_raw_negative():
    robot.move_at_speed_raw(x_speed=-100, y_speed=-50,
                            rotation_speed=-30, front_rotation_speed=0)
    start = time.monotonic()
    while time.monotonic() - start < 0.5:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

test("move_at_speed_raw — all negative speeds for 0.5s", test_speed_raw_negative)


# ================================================================
#  HIGH-LEVEL DISTANCE (with pivot)
# ================================================================

# 22. Straight, pivot at center
def test_dist_pivot_center():
    robot.move_by_distance(distance_mm=300, x_speed=100, y_speed=0,
                           rotation_speed=0, center_x_mm=0, center_y_mm=0,
                           rotate_chassis=True)
    robot.run_to_position()

test("move_by_distance — forward 300mm, pivot=(0,0)", test_dist_pivot_center)

# 23. Rotating around off-center pivot
def test_dist_pivot_offset():
    robot.move_by_distance(distance_mm=400, x_speed=0, y_speed=0,
                           rotation_speed=45, center_x_mm=100, center_y_mm=0,
                           rotate_chassis=True)
    robot.run_to_position()

test("move_by_distance — rotate 45deg/s, pivot=(100,0)", test_dist_pivot_offset)

# 24. Pivot behind robot
def test_dist_pivot_behind():
    robot.move_by_distance(distance_mm=300, x_speed=0, y_speed=0,
                           rotation_speed=30, center_x_mm=-150, center_y_mm=0,
                           rotate_chassis=True)
    robot.run_to_position()

test("move_by_distance — rotate, pivot=(-150,0) behind robot", test_dist_pivot_behind)

# 25. Pivot to the side
def test_dist_pivot_side():
    robot.move_by_distance(distance_mm=300, x_speed=0, y_speed=0,
                           rotation_speed=30, center_x_mm=0, center_y_mm=200,
                           rotate_chassis=True)
    robot.run_to_position()

test("move_by_distance — rotate, pivot=(0,200) to the side", test_dist_pivot_side)

# 26. rotate_chassis=False (front stays fixed)
def test_dist_no_chassis_rotate():
    robot.move_by_distance(distance_mm=300, x_speed=0, y_speed=0,
                           rotation_speed=30, center_x_mm=100, center_y_mm=0,
                           rotate_chassis=False)
    robot.run_to_position()

def check_front_stays():
    a = robot.get_chassis_angle()
    f = robot.get_front_angle()
    return (True, f"chassis={a:.1f} front={f:.1f}")

test("move_by_distance — rotate_chassis=False, pivot=(100,0)", test_dist_no_chassis_rotate, check_front_stays)


# ================================================================
#  HIGH-LEVEL TIME (with pivot)
# ================================================================

# 27. Rotate around pivot for time
def test_time_pivot():
    robot.move_by_time(time_s=1.0, x_speed=0, y_speed=0,
                       rotation_speed=45, center_x_mm=0, center_y_mm=0,
                       rotate_chassis=True)
    robot.run_to_position()

test("move_by_time — rotate 45deg/s, 1s, pivot=(0,0)", test_time_pivot)

# 28. Off-center pivot
def test_time_pivot_offset():
    robot.move_by_time(time_s=1.0, x_speed=0, y_speed=0,
                       rotation_speed=30, center_x_mm=200, center_y_mm=100,
                       rotate_chassis=True)
    robot.run_to_position()

test("move_by_time — rotate 30deg/s, 1s, pivot=(200,100)", test_time_pivot_offset)

# 29. Negative rotation around pivot
def test_time_pivot_neg():
    robot.move_by_time(time_s=1.0, x_speed=0, y_speed=0,
                       rotation_speed=-60, center_x_mm=100, center_y_mm=0,
                       rotate_chassis=True)
    robot.run_to_position()

test("move_by_time — rotate -60deg/s, 1s, pivot=(100,0)", test_time_pivot_neg)


# ================================================================
#  HIGH-LEVEL SPEED (with pivot)
# ================================================================

# 30. Forward + pivot
def test_speed_pivot():
    robot.move_at_speed(x_speed=100, y_speed=50,
                        rotation_speed=0, center_x_mm=0, center_y_mm=0,
                        rotate_chassis=True)
    start = time.monotonic()
    while time.monotonic() - start < 1.0:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

test("move_at_speed — diagonal, pivot=(0,0), 1s", test_speed_pivot)

# 31. Orbiting off-center pivot
def test_speed_orbit():
    robot.move_at_speed(x_speed=0, y_speed=0,
                        rotation_speed=45, center_x_mm=150, center_y_mm=0,
                        rotate_chassis=True)
    start = time.monotonic()
    while time.monotonic() - start < 1.0:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

test("move_at_speed — orbit around pivot=(150,0), 1s", test_speed_orbit)


# ================================================================
#  HIGH-LEVEL ANGLE (with pivot)
# ================================================================

# 32. Positive angle, center pivot
def test_angle_pivot_center():
    robot.move_by_angle(x_speed=0, y_speed=0, angle_deg=45,
                        rotation_speed=30, center_x_mm=0, center_y_mm=0,
                        rotate_chassis=True)
    robot.run_to_position()

test("move_by_angle — +45 deg, pivot=(0,0)", test_angle_pivot_center)

# 33. Negative angle, center pivot
def test_angle_pivot_neg():
    robot.move_by_angle(x_speed=0, y_speed=0, angle_deg=-45,
                        rotation_speed=30, center_x_mm=0, center_y_mm=0,
                        rotate_chassis=True)
    robot.run_to_position()

test("move_by_angle — -45 deg, pivot=(0,0)", test_angle_pivot_neg)

# 34. Off-center pivot
def test_angle_pivot_offset():
    robot.move_by_angle(x_speed=0, y_speed=0, angle_deg=90,
                        rotation_speed=45, center_x_mm=100, center_y_mm=50,
                        rotate_chassis=True)
    robot.run_to_position()

test("move_by_angle — +90 deg, pivot=(100,50)", test_angle_pivot_offset)

# 35. Off-center, rotate_chassis=False
def test_angle_pivot_no_chassis():
    robot.move_by_angle(x_speed=0, y_speed=0, angle_deg=60,
                        rotation_speed=30, center_x_mm=100, center_y_mm=0,
                        rotate_chassis=False)
    robot.run_to_position()

def check_angle_no_chassis():
    a = robot.get_chassis_angle()
    f = robot.get_front_angle()
    return (True, f"chassis={a:.1f} front={f:.1f}")

test("move_by_angle — +60 deg, pivot=(100,0), rotate_chassis=False", test_angle_pivot_no_chassis, check_angle_no_chassis)


# ================================================================
#  MOTOR COMMANDS
# ================================================================

# 36. move_at_speed_motors — all positive
def test_motors_all_pos():
    robot.move_at_speed_motors([80, 80, 80])
    start = time.monotonic()
    while time.monotonic() - start < 0.5:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

test("move_at_speed_motors — [80, 80, 80] for 0.5s", test_motors_all_pos)

# 37. Mixed speeds
def test_motors_mixed():
    robot.move_at_speed_motors([100, -100, 50])
    start = time.monotonic()
    while time.monotonic() - start < 0.5:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

test("move_at_speed_motors — [100, -100, 50] for 0.5s", test_motors_mixed)

# 38. All negative
def test_motors_all_neg():
    robot.move_at_speed_motors([-60, -60, -60])
    start = time.monotonic()
    while time.monotonic() - start < 0.5:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

test("move_at_speed_motors — [-60, -60, -60] for 0.5s", test_motors_all_neg)

# 39. run_motor_for_time — each motor
def test_motor_time_0():
    robot.run_motor_for_time(motor_id=0, speed=100, time_s=0.5)
    robot.run_to_position()

test("run_motor_for_time — motor 0, 100mm/s, 0.5s", test_motor_time_0)

def test_motor_time_1():
    robot.run_motor_for_time(motor_id=1, speed=-80, time_s=0.5)
    robot.run_to_position()

test("run_motor_for_time — motor 1, -80mm/s (reverse), 0.5s", test_motor_time_1)

def test_motor_time_2():
    robot.run_motor_for_time(motor_id=2, speed=120, time_s=0.5)
    robot.run_to_position()

test("run_motor_for_time — motor 2, 120mm/s, 0.5s", test_motor_time_2)

# 40. run_motor_for_distance
def test_motor_dist_0():
    robot.run_motor_for_distance(motor_id=0, speed=80, distance_mm=200)
    robot.run_to_position()

test("run_motor_for_distance — motor 0, 200mm", test_motor_dist_0)

def test_motor_dist_reverse():
    robot.run_motor_for_distance(motor_id=1, speed=-80, distance_mm=150)
    robot.run_to_position()

test("run_motor_for_distance — motor 1, -80mm/s (reverse), 150mm", test_motor_dist_reverse)

# 41. start_motor + stop_motor — each motor
def test_start_stop_0():
    robot.start_motor(motor_id=0, speed=120)
    start = time.monotonic()
    while time.monotonic() - start < 0.3:
        robot.run()
        time.sleep(0.02)
    robot.stop_motor(motor_id=0)
    robot.run_to_position()

test("start_motor + stop_motor — motor 0", test_start_stop_0)

def test_start_stop_1():
    robot.start_motor(motor_id=1, speed=-100)
    start = time.monotonic()
    while time.monotonic() - start < 0.3:
        robot.run()
        time.sleep(0.02)
    robot.stop_motor(motor_id=1)
    robot.run_to_position()

test("start_motor + stop_motor — motor 1, reverse", test_start_stop_1)

def test_start_stop_2():
    robot.start_motor(motor_id=2, speed=80)
    start = time.monotonic()
    while time.monotonic() - start < 0.3:
        robot.run()
        time.sleep(0.02)
    robot.stop_motor(motor_id=2)
    robot.run_to_position()

test("start_motor + stop_motor — motor 2", test_start_stop_2)


# ================================================================
#  QUEUE AND STOP
# ================================================================

# 42. clear_command_queue
def test_clear_queue():
    robot.move_by_distance_raw(distance_mm=5000, x_speed=50, y_speed=0,
                               rotation_speed=0, front_rotation_speed=0)
    robot.move_by_distance_raw(distance_mm=5000, x_speed=50, y_speed=0,
                               rotation_speed=0, front_rotation_speed=0)
    robot.clear_command_queue()
    robot.stop()
    robot.run_to_position()

test("clear_command_queue — queue 2 long commands then clear", test_clear_queue)

# 43. stop interrupts current command
def test_stop_interrupt():
    x0 = robot.get_distance_traveled_x()
    robot.move_by_distance_raw(distance_mm=10000, x_speed=200, y_speed=0,
                               rotation_speed=0, front_rotation_speed=0)
    start = time.monotonic()
    while time.monotonic() - start < 0.3:
        robot.run()
        time.sleep(0.02)
    robot.stop()
    robot.run_to_position()

def check_stop_interrupt():
    return (True, f"x={robot.get_distance_traveled_x():.1f} (should be much less than 10000)")

test("stop — interrupt a 10000mm move after 0.3s", test_stop_interrupt, check_stop_interrupt)


# ================================================================
#  ERROR CASES
# ================================================================

# 44. run_motor_for_time — motor index out of range
def test_err_motor_time_oor():
    robot.run_motor_for_time(motor_id=99, speed=100, time_s=1.0)
    robot.run_to_position()

test_expect_error("run_motor_for_time — motor_id=99 (out of range)", test_err_motor_time_oor)

# 45. run_motor_for_distance — motor index out of range
def test_err_motor_dist_oor():
    robot.run_motor_for_distance(motor_id=50, speed=80, distance_mm=200)
    robot.run_to_position()

test_expect_error("run_motor_for_distance — motor_id=50 (out of range)", test_err_motor_dist_oor)

# 46. start_motor — motor index out of range
def test_err_start_motor_oor():
    robot.start_motor(motor_id=255, speed=100)
    start = time.monotonic()
    while time.monotonic() - start < 0.5:
        robot.run()
        time.sleep(0.02)

test_expect_error("start_motor — motor_id=255 (out of range)", test_err_start_motor_oor)

# 47. stop_motor — motor index out of range
def test_err_stop_motor_oor():
    robot.stop_motor(motor_id=100)
    start = time.monotonic()
    while time.monotonic() - start < 0.5:
        robot.run()
        time.sleep(0.02)

test_expect_error("stop_motor — motor_id=100 (out of range)", test_err_stop_motor_oor)

# 48. move_at_speed_motors — too many motors
def test_err_too_many_motors():
    robot.move_at_speed_motors([100, 100, 100, 100, 100, 100])
    start = time.monotonic()
    while time.monotonic() - start < 0.5:
        robot.run()
        time.sleep(0.02)

test_expect_error("move_at_speed_motors — 6 motors (robot has 3)", test_err_too_many_motors)


# ================================================================
#  TELEMETRY
# ================================================================

# 49. All telemetry getters
def test_telemetry():
    robot.move_by_distance_raw(distance_mm=100, x_speed=80, y_speed=0,
                               rotation_speed=0, front_rotation_speed=0)
    robot.run_to_position()
    robot.run()
    print(f"  distance_x        = {robot.get_distance_traveled_x():.1f}")
    print(f"  distance_y        = {robot.get_distance_traveled_y():.1f}")
    print(f"  velocity_x        = {robot.get_velocity_x():.1f}")
    print(f"  velocity_y        = {robot.get_velocity_y():.1f}")
    print(f"  front_angle       = {robot.get_front_angle():.1f}")
    print(f"  chassis_angle     = {robot.get_chassis_angle():.1f}")
    print(f"  angular_velocity  = {robot.get_chassis_angular_velocity():.1f}")
    for i in range(3):
        print(f"  wheel {i} speed={robot.get_wheel_speed(i):.1f} "
              f"dist={robot.get_wheel_distance(i):.1f}")

test("telemetry — all getters after 100mm move", test_telemetry)


# ================================================================
#  SUMMARY
# ================================================================
robot.disconnect()
print("=" * 50)
print(f"Results: {passed} passed, {failed} failed, {passed + failed} total")
print("Disconnected")
